### ISSUE TITLE
Allowed memory size of 262144 bytes exhausted

### ISSUE THREAD

**Issue by davmak** [Zookal/Magento-MyTableOptimization#1]
When I type the command in ssh I got this message: "Allowed memory size of 262144 bytes exhausted (tried to allocate 20 bytes)".

I have increased memory-limit, php_value memory_limit but no success.

Any idea ?

**Comment by blopa** [comment]
Are you in a shared host?

**Comment by davmak** [comment]
Hello,

No. dedicated.

**Comment by blopa** [comment]
Hi. I'm no expert, but try adding memcache and swap memory to your host.

**Comment by davmak** [comment]
I already have Redis.

**Comment by blopa** [comment]
That's weird. Sorry I can't help more.

**Comment by davmak** [comment]
thank you anyway.

**Comment by SchumacherFM** [comment]
You've increased the memory limit for PHP in Apache or Nginx env. You must increase the mem limit for PHP on the CLI via php.ini file for example.

**Comment by davmak** [comment]
No, In did it both in  apache and php.ini.

memory_limit = 2048M
php_value memory_limit = 2048M

The issue is always here.
