### ISSUE TITLE
2 years later: is it still working?

### ISSUE THREAD

**Issue by shirtsofholl** [Zookal/Magento-MyTableOptimization#2]
2 years later: is it still working?

We run mage 1.9.2.4 and interested in using this!

good work from DU

**Comment by SchumacherFM** [comment]
Of course. All good here!

**Comment by shirtsofholl** [comment]
Superb! I used a simple script but this works better. 

One other question, for the options:
Set which tables to include in the optimization process
Set which tables to exclude during the optimization process. Note that include overrides the exclude option.

if you select not tables: does this mean ALL?

(question is that when tables are added to Magento how does it automatically include them)

**Comment by seansan** [comment]
FYI

l/shell# php tableOpt.php run
PHP Fatal error:  Uncaught Error: Call to a member function setCli() on boolean in shell/tableOpt.php:36
Stack trace:
#0 shell/tableOpt.php(68): Zookal_Table_Opt->run()
#1 {main}
  thrown in shell/tableOpt.php on line 36
